### ISSUE TITLE
Suggestion: rename "ngrxControl" directive to "ngrxFormControl" 

### ISSUE THREAD

**Issue by hansfuchs** [NiklasPor/ngrx-clean-forms#1]
Hey man,

I really like your work, however I feel that the ngrxControl directive should rather be named ngrxFormControl to increase clarity.

This is all for now.

**Comment by NiklasPor** [comment]
Thanks!

I agree, `ngrxFormControl` sounds way more intuitive.
I'll include the change in the next major release.

**Comment by NiklasPor** [comment]
#4
