### ISSUE TITLE
Change fast/equals peer-dependency to dependency

### ISSUE THREAD

**Issue by NiklasPor** [NiklasPor/ngrx-clean-forms#24]
@PhilippSeitz

**Comment by NiklasPor** [comment]
Not sure about this. Adding direct dependencies for reusable packages is quite the controversial thing to do:

https://github.com/ng-packagr/ng-packagr/issues/716

**Comment by PhilippSeitz** [comment]
any updates on this?

**Comment by NiklasPor** [comment]
I'll include it in the next major release together with Angular 9 support.
